import { NFTCollectible, Transaction } from "@/lib/types";

export const eventsData = [
  {
    id: 1,
    src: "/events/comic-con.jpg",
    alt: "Comic con",
    link: "",
    date: "September 6, 2025",
    title: "Comic Con 2025",
    subtitle:
      "Experience a day of creativity and connection at our annual community event! ",
  },
  {
    id: 2,
    src: "/events/tech-summit.jpg",
    alt: "tech summit",
    link: "",
    date: "May 21, 2025",
    title: "Tech Innovation Summit 2025",
    subtitle:
      "Join industry leaders to explore the latest in technology and innovation.",
  },
  {
    id: 3,
    src: "/events/arts-fair.jpg",
    alt: "arts fair",
    link: "",
    date: "June 10, 2025",
    title: "Arts & Crafts Fair 2025",
    subtitle: "Showcase your talents and discover new art at our annual fair!",
  },
];

export const creatorTransactions: Transaction[] = [
  {
    id: "1",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "2",
    type: "earning",
    status: "completed",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "3",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "4",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "5",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "6",
    type: "gift",
    status: "completed",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "7",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "8",
    type: "purchase",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "9",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "10",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "11",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "12",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "13",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "14",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
];

export const nftData: NFTCollectible[] = [
  {
    id: "1",
    name: "Elena's Awakening - Artwork Cover",
    description: "Elena's Awakening - Artwork Cover",
    image: "/events/anime-con.jpg",
    status: "active",
    total_copies: 36,
    sold_copies: 18,
    price: 10,
    commission: 10,
  },
  {
    id: "2",
    name: "Mystic Realms - Artwork Cover",
    description: "Mystic Realms - Artwork Cover",
    image: "/events/anime-con.jpg",
    status: "scheduled",
    total_copies: 20,
    sold_copies: 0,
    price: 15,
    commission: 12,
  },
  {
    id: "3",
    name: "Shadows of Tomorrow - Artwork Cover",
    description: "Shadows of Tomorrow - Artwork Cover",
    image: "/events/anime-con.jpg",
    status: "active",
    total_copies: 50,
    sold_copies: 30,
    price: 20,
    commission: 15,
  },
  {
    id: "4",
    name: "Journey's End - Artwork Cover",
    description: "Journey's End - Artwork Cover",
    image: "/events/anime-con.jpg",
    status: "sold out",
    total_copies: 40,
    sold_copies: 40,
    price: 25,
    commission: 18,
  },
  {
    id: "5",
    name: "Elena's Awakening - Artwork Cover",
    description: "Elena's Awakening - Artwork Cover",
    image: "/events/anime-con.jpg",
    status: "active",
    total_copies: 36,
    sold_copies: 18,
    price: 10,
    commission: 10,
  },
  {
    id: "6",
    name: "Mystic Realms - Artwork Cover",
    description: "Mystic Realms - Artwork Cover",
    image: "/events/anime-con.jpg",
    status: "scheduled",
    total_copies: 20,
    sold_copies: 0,
    price: 15,
    commission: 12,
  },
  {
    id: "7",
    name: "Shadows of Tomorrow - Artwork Cover",
    description: "Shadows of Tomorrow - Artwork Cover",
    image: "/events/anime-con.jpg",
    status: "active",
    total_copies: 50,
    sold_copies: 30,
    price: 20,
    commission: 15,
  },
  {
    id: "8",
    name: "Journey's End - Artwork Cover",
    description: "Journey's End - Artwork Cover",
    image: "/events/anime-con.jpg",
    status: "sold out",
    total_copies: 40,
    sold_copies: 40,
    price: 25,
    commission: 18,
  },
];
