// import { Chapter, Comic, NFTCollectible, Transaction } from "@/lib/types";

// export const eventsData = [
//   {
//     id: 1,
//     src: "/events/comic-con.jpg",
//     alt: "Comic con",
//     link: "https://www.straqa.events/nerdworkcomiccon",
//     date: "September 6, 2025",
//     title: "Comic Con 2025",
//     subtitle:
//       "Experience a day of creativity and connection at our annual community event! ",
//   },
//   {
//     id: 2,
//     src: "/events/tech-summit.jpg",
//     alt: "tech summit",
//     link: "",
//     date: "May 21, 2025",
//     title: "Tech Innovation Summit 2025",
//     subtitle:
//       "Join industry leaders to explore the latest in technology and innovation.",
//   },
//   {
//     id: 3,
//     src: "/events/arts-fair.jpg",
//     alt: "arts fair",
//     link: "",
//     date: "June 10, 2025",
//     title: "Arts & Crafts Fair 2025",
//     subtitle: "Showcase your talents and discover new art at our annual fair!",
//   },
// ];

// export const comicData: Comic[] = [
//   {
//     id: "1",
//     image: "/events/anime-con.jpg",
//     title: "Mystic Chronicles: The Awakening",
//     description: "Just a short description",
//     comicStatus: "draft",
//     noOfChapters: 3,
//     updatedAt: "24/07/2024",
//     genre: ["adventure", "fantasy", "historical"],
//     isPaid: true,
//     isOngoing: false,
//   },
//   {
//     id: "2",
//     image: "/events/anime-con.jpg",
//     title: "In My Head",
//     description: "Just a short description",
//     comicStatus: "draft",
//     noOfChapters: 3,
//     updatedAt: "24/07/2024",
//     genre: ["sci-fi", "romance", "thriller", "historical"],
//     ageRating: "Mature",

//     isPaid: false,
//     isOngoing: true,
//   },
//   {
//     id: "3",
//     image: "/events/anime-con.jpg",
//     title: "Totem: Vessel of the Gods",
//     description: "Just a short description",
//     comicStatus: "published",
//     noOfChapters: 3,
//     updatedAt: "24/07/2024",
//     genre: ["adventure", "sci-fi", "thriller", "historical"],
//     ageRating: "All",

//     isPaid: true,
//     isOngoing: false,
//   },
//   {
//     id: "4",
//     image: "/events/anime-con.jpg",
//     title: "Celestial Eyes",
//     description: "Just a short description",
//     comicStatus: "published",
//     noOfChapters: 3,
//     updatedAt: "24/07/2024",
//     genre: ["adventure", "fantasy", "mystery", "sci-fi"],
//     ageRating: "12 +",
//     isPaid: false,
//     isOngoing: true,
//   },
//   {
//     id: "5",
//     image: "/events/anime-con.jpg",
//     title: "This Side Up",
//     description: "Just a short description",
//     comicStatus: "scheduled",
//     noOfChapters: 3,
//     updatedAt: "24/07/2024",
//     genre: ["adventure", "superhero", "historical"],
//     isPaid: true,
//     isOngoing: false,
//   },
//   {
//     id: "6",
//     image: "/events/anime-con.jpg",
//     title: "Dream",
//     description: "Just a short description",
//     comicStatus: "scheduled",
//     noOfChapters: 3,
//     updatedAt: "24/07/2024",
//     genre: ["adventure", "mystery", "romance", "superhero"],
//     isPaid: false,
//     isOngoing: true,
//   },
//   {
//     id: "7",
//     image: "/events/anime-con.jpg",
//     title: "Shuri",
//     description: "Just a short description",
//     comicStatus: "upcoming",
//     noOfChapters: 3,
//     updatedAt: "24/07/2024",
//     genre: ["thriller", "superhero", "historical"],
//     isPaid: true,
//     isOngoing: false,
//   },
//   {
//     id: "8",
//     image: "/events/anime-con.jpg",
//     title: "The Ambassadors",
//     description: "Just a short description",
//     comicStatus: "upcoming",
//     noOfChapters: 3,
//     updatedAt: "24/07/2024",
//     genre: ["adventure", "mystery", "sci-fi"],
//     isPaid: false,
//     isOngoing: true,
//   },
// ];

// export const creatorTransactions: Transaction[] = [
//   {
//     id: "1",
//     type: "earning",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "2",
//     type: "earning",
//     status: "completed",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "3",
//     type: "earning",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "4",
//     type: "withdrawal",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "5",
//     type: "withdrawal",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "6",
//     type: "gift",
//     status: "completed",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "7",
//     type: "earning",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "8",
//     type: "purchase",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "9",
//     type: "earning",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "10",
//     type: "withdrawal",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "11",
//     type: "withdrawal",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "12",
//     type: "withdrawal",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "13",
//     type: "withdrawal",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
//   {
//     id: "14",
//     type: "withdrawal",
//     status: "pending",
//     description: "m@example.com",
//     amount: 50,
//     date: "08/04/25",
//   },
// ];

// export const chapterData: Chapter[] = [
//   {
//     id: "1",
//     image: "/events/anime-con.jpg",
//     title: "Mystic Chronicles: The Awakening",
//     summary: "Just a short description",
//     chapterStatus: "draft",
//     count: 3,
//     date: "24/07/2024",
//     read: true,
//     unlocked: true,
//   },
//   {
//     id: "2",
//     image: "/events/anime-con.jpg",
//     title: "Mystic Chronicles: The Awakening",
//     summary: "Just a short description",
//     chapterStatus: "draft",
//     count: 3,
//     date: "24/07/2024",
//     read: true,
//     unlocked: true,
//   },
//   {
//     id: "3",
//     image: "/events/anime-con.jpg",
//     title: "Mystic Chronicles: The Awakening",
//     summary: "Just a short description",
//     chapterStatus: "published",
//     count: 3,
//     date: "24/07/2024",
//     read: false,
//     unlocked: false,
//   },
//   {
//     id: "4",
//     image: "/events/anime-con.jpg",
//     title: "Mystic Chronicles: The Awakening",
//     summary: "Just a short description",
//     chapterStatus: "published",
//     count: 3,
//     date: "24/07/2024",
//     read: false,
//     unlocked: false,
//   },
//   {
//     id: "5",
//     image: "/events/anime-con.jpg",
//     title: "Mystic Chronicles: The Awakening",
//     summary: "Just a short description",
//     chapterStatus: "scheduled",
//     count: 3,
//     date: "24/07/2024",
//     read: false,
//     unlocked: false,
//   },
//   {
//     id: "6",
//     image: "/events/anime-con.jpg",
//     title: "Mystic Chronicles: The Awakening",
//     summary: "Just a short description",
//     chapterStatus: "scheduled",
//     count: 3,
//     date: "24/07/2024",
//     read: false,
//     unlocked: false,
//   },
//   {
//     id: "7",
//     image: "/events/anime-con.jpg",
//     title: "Mystic Chronicles: The Awakening",
//     summary: "Just a short description",
//     chapterStatus: "scheduled",
//     count: 3,
//     date: "24/07/2024",
//     read: false,
//     unlocked: false,
//   },
//   {
//     id: "8",
//     image: "/events/anime-con.jpg",
//     title: "Mystic Chronicles: The Awakening",
//     summary: "Just a short description",
//     chapterStatus: "published",
//     count: 3,
//     date: "24/07/2024",
//     read: false,
//     unlocked: false,
//   },
// ];

// export const nftData: NFTCollectible[] = [
//   {
//     id: "1",
//     name: "Elena's Awakening - Artwork Cover",
//     description: "Elena's Awakening - Artwork Cover",
//     image: "/events/anime-con.jpg",
//     status: "active",
//     total_copies: 36,
//     sold_copies: 18,
//     price: 10,
//     commission: 10,
//   },
//   {
//     id: "2",
//     name: "Mystic Realms - Artwork Cover",
//     description: "Mystic Realms - Artwork Cover",
//     image: "/events/anime-con.jpg",
//     status: "scheduled",
//     total_copies: 20,
//     sold_copies: 0,
//     price: 15,
//     commission: 12,
//   },
//   {
//     id: "3",
//     name: "Shadows of Tomorrow - Artwork Cover",
//     description: "Shadows of Tomorrow - Artwork Cover",
//     image: "/events/anime-con.jpg",
//     status: "active",
//     total_copies: 50,
//     sold_copies: 30,
//     price: 20,
//     commission: 15,
//   },
//   {
//     id: "4",
//     name: "Journey's End - Artwork Cover",
//     description: "Journey's End - Artwork Cover",
//     image: "/events/anime-con.jpg",
//     status: "sold out",
//     total_copies: 40,
//     sold_copies: 40,
//     price: 25,
//     commission: 18,
//   },
//   {
//     id: "5",
//     name: "Elena's Awakening - Artwork Cover",
//     description: "Elena's Awakening - Artwork Cover",
//     image: "/events/anime-con.jpg",
//     status: "active",
//     total_copies: 36,
//     sold_copies: 18,
//     price: 10,
//     commission: 10,
//   },
//   {
//     id: "6",
//     name: "Mystic Realms - Artwork Cover",
//     description: "Mystic Realms - Artwork Cover",
//     image: "/events/anime-con.jpg",
//     status: "scheduled",
//     total_copies: 20,
//     sold_copies: 0,
//     price: 15,
//     commission: 12,
//   },
//   {
//     id: "7",
//     name: "Shadows of Tomorrow - Artwork Cover",
//     description: "Shadows of Tomorrow - Artwork Cover",
//     image: "/events/anime-con.jpg",
//     status: "active",
//     total_copies: 50,
//     sold_copies: 30,
//     price: 20,
//     commission: 15,
//   },
//   {
//     id: "8",
//     name: "Journey's End - Artwork Cover",
//     description: "Journey's End - Artwork Cover",
//     image: "/events/anime-con.jpg",
//     status: "sold out",
//     total_copies: 40,
//     sold_copies: 40,
//     price: 25,
//     commission: 18,
//   },
// ];
