import { NFTCollectible, Transaction } from "@/lib/types";

export const eventsData = [
  {
    id: 1,
    src: "https://res.cloudinary.com/dk4gmufzn/image/upload/v1759857408/arts-fair_ira10b.jpg",
    alt: "Comic con",
    link: "",
    date: "September 6, 2025",
    title: "Comic Con 2025",
    subtitle:
      "Experience a day of creativity and connection at our annual community event! ",
  },
  {
    id: 2,
    src: "https://res.cloudinary.com/dk4gmufzn/image/upload/v1759857380/tech-summit_hkj9mz.jpg",
    alt: "tech summit",
    link: "",
    date: "May 21, 2025",
    title: "Tech Innovation Summit 2025",
    subtitle:
      "Join industry leaders to explore the latest in technology and innovation.",
  },
  {
    id: 3,
    src: "https://res.cloudinary.com/dk4gmufzn/image/upload/v1759857408/arts-fair_ira10b.jpg",
    alt: "arts fair",
    link: "",
    date: "June 10, 2025",
    title: "Arts & Crafts Fair 2025",
    subtitle: "Showcase your talents and discover new art at our annual fair!",
  },
];

export const creatorTransactions: Transaction[] = [
  {
    id: "1",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "2",
    type: "earning",
    status: "completed",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "3",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "4",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "5",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "6",
    type: "gift",
    status: "completed",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "7",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "8",
    type: "purchase",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "9",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "10",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "11",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "12",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "13",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "14",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
];
